<?php

  $contentblocks = [
  [ 'page' => 'contact',
    'section' => 0,
    'title' => 'Praat erover',
    'body' => 'Allereerst kan je erover praten met de CLB dienst van je school. Deze mensen zullen je graag verder helpen. Anderzijds kan je ook terecht bij je zorgleerkracht op school. Deze persoon gaat er alles aan doen om je terug op je gemak te stellen. Als laatste, en zeker daarom niet de minst beste oplossing, is praten met je ouders. Die zullen dan de juiste personen aanspreken in jouw plaats.',
  ],
  [ 'page' => 'contact',
    'section' => 1,
    'title' => 'Online chats en hulplijnen',
    'body' => 'Als je niet goed weet tegen wie eerst te praten en heb je liever eerst een anoniem gesprek met iemand online, dan kan je terecht bij volgende online chats waarbij ook deze mensen je graag verder helpen.',
  ],
  [ 'page' => 'contact',
    'section' => 2,
    'title' => 'JAC',
    'body' => 'Het JAC helpt jongeren met al hun vragen en problemen. Problemen thuis? Op zoek naar je eigen stek? Vragen over seks? Slachtoffer van geweld of misbruik? Geldproblemen? Vragen over drugs? Of over pesten? Informatie nodig om zelfstandig te wonen? Of over je rechten en plichten? … Je kan bij het JAC terecht met elke vraag.',
  ],
  [ 'page' => 'contact',
    'section' => 3,
    'title' => 'AWEL',
    'body' => 'Awel luistert naar alle kinderen en jongeren met een vraag, een verhaal en/of een probleem. Alle kinderen en jongeren kunnen hen anoniem contacteren over alles wat ze bezighoudt. Ze zijn er voor hen door te luisteren, mee te voelen en mee te denken.',
  ],
  [ 'page' => 'contact',
    'section' => 4,
    'title' => 'Tele-onthaal',
    'body' => 'Soms moet je al je moed bijeen rapen voor een gesprek. Of vraag je je af of zo’n gesprek wel veilig is. Om het voor jou zo makkelijk mogelijk te maken om te praten, houden we de drempel zo laag mogelijk.',
  ],
  [ 'page' => 'contact',
    'section' => 5,
    'title' => 'Nu Praat Ik Erover',
    'body' => 'Ben je minderjarig en heb je vragen over seksueel misbruik? Word je seksueel lastig gevallen? Word je vaak uitgescholden? Is er iemand die je fysiek pijn doet? Ken je iemand met zo’n probleem?',
  ],
  [ 'page' => 'contact',
    'section' => 6,
    'title' => 'CLB Chat',
    'body' => 'Op de chat praat je met een medewerker van het CLB. Je kan je verhaal vertellen, een vraag stellen, … of samen met je chatbegeleider bekijken wat je zou willen bereiken, en hoe je dat kan aanpakken. De CLB-medewerker chat enkel met jou. Een chatgesprek duurt maximum 45 minuten, zodat ook andere leerlingen een kans krijgen om te chatten.',
  ],
  [ 'page' => 'contact',
    'section' => 7,
    'title' => 'Hulplijn 1712',
    'body' => 'Bij de hulplijn 1712 kan je terecht met vragen over (lichamelijk, psychisch of seksueel) geweld, misbruik en kindermishandeling. Je wordt geholpen door hulpverleners van de centra voor algemeen welzijnswerken de vertrouwenscentra kindermishandeling.',
  ],
  [ 'page' => 'contact',
    'section' => 8,
    'title' => 'Aangifte doen',
    'body' => 'Heb je er met iemand over gepraat en is het duidelijk geworden dat de feiten strafbaar zijn of dat er dringende politiehulp nodig is, dan kan je terecht op het noodnummer van de politie. Dit is 101.

Is de hulp niet dringend? Dan kan je De Blauwe Lijn bellen. Dit is 0800 123 12. Ook kan een online afspraak maken met de lokale politie bij het Blauwe Loket op <a href="https://www.politieantwerpen.be/e-loket">https://www.politieantwerpen.be/e-loket</a>.',
  ],
];
